version: "3"
services:
  springboot-app:
    container_name: spring-app
    image: springboot-app
    build: .
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: db_springboot_backend
      MYSQL_ROOT_PASSWORD: root